DROP TABLE item;
CREATE TABLE item (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    name VARCHAR2(100),
    price NUMBER,
    total_number NUMBER,
    PRIMARY KEY (id)
);

SELECT * FROM item;
INSERT INTO item (name, price) VALUES ('item1', 50);

